### ISSUE TITLE
LazOpenGLContext

### ISSUE THREAD

**Issue by theavege** [PascalCorpsman/sandtris#2]
Where I can find [LazOpenGLContext](https://packages.lazarus-ide.org)?
If it isn't a secret, why you don't use [Castle_Game_Engine](https://wiki.freepascal.org/Castle_Game_Engine) for the game?

**Comment by PascalCorpsman** [comment]
As described in the Readme, LazOpenGLContext is part of the default Lazarus installation, but you need to install it manually (see this forum entry for more informations: https://forum.lazarus.freepascal.org/index.php?topic=35807.0 )
